name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Check out latest code
      uses: actions/checkout@v4

    - name: Copy files to app directory
      run: |
        cp -rf ./app/* /opt/weather-pi/app/
        echo "Files copied to /opt/weather-pi/app/"

    - name: Install dependencies
      run: |
        /opt/weather-pi/venv/bin/pip install -r /opt/weather-pi/app/requirements.txt
        echo "Dependencies installed"

    - name: Reload FastAPI service (graceful restart)
      run: |
        # daemon-reload는 .service 파일이 바뀔 때만 필요합니다.
        # 앱 코드만 바뀌었으므로 reload만 실행합니다.
        sudo systemctl reload weather-pi.service
        echo "Service gracefully reloaded"

    - name: Check service status
      run: |
        # || true : 서비스가 'failed' 상태여도 CI는 성공으로 처리 (상태 보고용)
        sudo systemctl status weather-pi.service --no-pager -l || true